language: c
sudo: false
os:
  - linux
compiler:
  - clang
matrix:
  exclude:
    - os: osx
      compiler: gcc
addons:
  apt:
    packages:
      - yasm
      - diffutils
cache:
  directories:
    - ffmpeg-samples
before_install:
  - git fetch --depth=1000000
  - openssl aes-256-cbc -K $encrypted_9601c2dd51ac_key -iv $encrypted_9601c2dd51ac_iv
    -in .travis/ssh_key.enc -out .travis/ssh_key -d
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update --all; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install yasm; fi
script:
  - mkdir -p ffmpeg-samples
  - rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ ffmpeg-samples
  - cp -a .travis $HOME/ffmpeg-travis
  - git reset --hard HEAD^
  - sh $HOME/ffmpeg-travis/fate.sh $HOME/ffmpeg-travis/fate_config.sh
